### ISSUE TITLE
rights missing, ERROR crt1.so

### ISSUE THREAD

**Issue by freaksdd** [Kukkimonsuta/rpi-buildqt#1]
Hi,
i have tested your work an found some problems with Linux Mint 18.1 (64-Bit) and RPi2.
(1.) 
- **2_sync.sh** - "fix links"
the script have no execute rights. at this part, the script is exiting
- when you sync the pi an the show you issue (starting the 2_sync.sh from the terminal) like, "rsync cant read /usr/.......
the user have to give there rights for READ (that was a problem with my pi, because i had qt5.6 on it, before i have testing your scripts)

(2.) 64-Bit Version -> **3.0_build_qtbase.sh**
for 64-Bit Version you need the /arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-
and please add `-no-icu` command at `./configure` for the issue with `crt1.so`

Have a nice day

**Comment by Kukkimonsuta** [comment]
`gcc-linaro-arm-linux-gnueabihf-raspbian-x64` is outdated toolchain that causes the `crt1.so` issues, so this guide will stay on `arm-rpi-4.9.3-linux-gnueabihf` only for now.

I'll try to resolve the rest when I get some time for pi again.

**Comment by Kukkimonsuta** [comment]
- exec rights shoud be fixed
 - compiler will stay `arm-rpi-4.9.3-linux-gnueabihf`
 - sync should be now `sudo`ed
