### ISSUE TITLE
dev: missing packages

### ISSUE THREAD

**Issue by maitredede** [Kukkimonsuta/rpi-buildqt#12]
Hi,

I am trying the dev branch. I am following the readme and I have errors.
I am using a fresh burned raspbian lite. At step 3, when "some more libs I added...", I have :
`Package 'gcc-multilib' has no installation candidate` and `Can't find pabkage g++-multilib`

My apt sources are the default ones with uncommented "deb-src" lines, and the reporitory of [Mono](http://www.mono-project.com/download/#download-lin-raspbian).

**Comment by maitredede** [comment]
Same for `libx32gcc-4.8-dev`.

**Comment by Kukkimonsuta** [comment]
The dev branch is work in progress, instruction are not finished. I've removed unconfirmed steps for now.

Currently `dev` can build QT `5.8` and `5.9` without `qtscript` and `qtwebengine`

**Comment by Kukkimonsuta** [comment]
I'm also exprimenting with gstreamer, so if piomxtextures is your goal then do the oposite and remove gstreamer packages :)

**Comment by maitredede** [comment]
:) I am experimenting `qtwebengine`. I have an app running with `qtwebkit` on the available precompiled version of Qt available on the pi, Qt 5.3.

**Comment by Kukkimonsuta** [comment]
I have pushed another commit. `qtwebengine` still doesn't build for me, but its getting closer.

**Comment by Kukkimonsuta** [comment]
```
[2/6774] ACTION //v8:run_mkpeephole(/home/lukas/raspi-qt-5.9/src/qtwebengine/src/toolchain:target)
FAILED: gen/v8/bytecode-peephole-table.cc
/usr/bin/python2 ../../3rdparty/chromium/v8/tools/run.py ./v8_snapshot/mkpeephole gen/v8/bytecode-peephole-table.cc
Traceback (most recent call last):
  File "../../3rdparty/chromium/v8/tools/run.py", line 12, in <module>
    sys.exit(subprocess.call(sys.argv[1:]))
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
[3/6774] ACTION //v8:run_mkpeephole(/home/lukas/raspi-qt-5.9/src/qtwebengine/src/toolchain:v8_snapshot)
FAILED: v8_snapshot/gen/v8/bytecode-peephole-table.cc
/usr/bin/python2 ../../3rdparty/chromium/v8/tools/run.py ./v8_snapshot/mkpeephole v8_snapshot/gen/v8/bytecode-peephole-table.cc
Traceback (most recent call last):
  File "../../3rdparty/chromium/v8/tools/run.py", line 12, in <module>
    sys.exit(subprocess.call(sys.argv[1:]))
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
[5/6774] AR v8_snapshot/obj/v8/libv8_libplatform.a
ninja: build stopped: subcommand failed.
Makefile.gn_run:372: recipe for target 'run_ninja' failed
make[3]: *** [run_ninja] Error 1
make[3]: Leaving directory '/home/lukas/raspi-qt-5.9/src/qtwebengine/src/core'
Makefile:80: recipe for target 'sub-gn_run-pro-make_first' failed
make[2]: *** [sub-gn_run-pro-make_first] Error 2
make[2]: Leaving directory '/home/lukas/raspi-qt-5.9/src/qtwebengine/src/core'
Makefile:77: recipe for target 'sub-core-make_first' failed
make[1]: *** [sub-core-make_first] Error 2
make[1]: Leaving directory '/home/lukas/raspi-qt-5.9/src/qtwebengine/src'
Makefile:46: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2
```

I'm stuck at this when building `qtwebengine`.

@zevero @matthewmgamble have you encountered this? Any hints?

**Comment by zevero** [comment]
@MaitreDede what is your host system? I use debian stretch amd64. But those packages exist on ubuntu as well:
https://packages.ubuntu.com/search?keywords=g%2B%2B-multilib
But this and some others I needed only for an error that came up with qtwebengine on 5.9 that when googled will lead you quickly to hints that this (these) packages are needed.

**Comment by maitredede** [comment]
@zevero I was trying to get them from the pi, not the host. My host is Bash on Ubuntu on Windows (Ubuntu 16.04 x64). I am following the dev readme, and will try to get webengine working. Thanks.

**Comment by maitredede** [comment]
I have gone as far : 

- can't compile QtScript :
```
In file included from ../3rdparty/javascriptcore/JavaScriptCore/config.h:26:0,
                 from ../3rdparty/javascriptcore/JavaScriptCore/pcre/pcre_compile.cpp:44:
../3rdparty/javascriptcore/JavaScriptCore/wtf/Platform.h:370:6: error: #error "Not supported ARM architecture"
 #    error "Not supported ARM architecture"
```
I removed it from my package list (the actual 5.9 one) and going further...

- can't compile webengine : 
```
bootstrap complete.  rebuilding...
[27/27] LINK ninja
  Reading /home/damien/raspi/src/qtwebengine/src/buildtools/gn.pro
Building gn manually in a temporary directory for bootstrapping...
ninja: Entering directory `/home/damien/raspi/src/qtwebengine/src/3rdparty/chromium/tools/gn/out/Release'
[330/330] LINK gn
Building gn using itself to out/Release...
ERROR at //BUILD.gn:74:1: Can't load input file.
group("gn_all") {
^----------------
Unable to load:
  /home/damien/raspi/src/qtwebengine/src/toolchain/BUILD.gn
I also checked in the secondary tree for:
  /home/damien/raspi/src/qtwebengine/src/toolchain/BUILD.gn
```
The directory `~/raspi/src/qtwebengine/src/toolchain` is missing.

I restarted the `4.1_build_modules.sh` script a second time. Seams to start building.

I have errors related to posix about `/proc/xxx/stat` but I think it is due to Bash on Ubuntu on Windows. 

Got the same error : `FAILED: gen/v8/bytecode-peephole-table.cc` [...] `OSError: [Errno 8] Exec format error`

**Comment by zevero** [comment]
I just cloned the new dev branch and am testing 5.9. Just had exactly the same error and restarting the script for qtwebengine did start building as well. I will edit my post next morning...

**Comment by maitredede** [comment]
The [comment here](https://github.com/nodejs/node/issues/9707#issuecomment-268776355) talks about cross-compilation errors. Maybe it can be a clue...

**Comment by zevero** [comment]
My 5.9 qtwebengine build with the current dev scripts (changed only RPIDEV_ROOT and I used my previous sysroot) had NO errors.
However I needed to restart `4.1_build_modules.sh qtwebengine` as explained above. (I think I had this before as well ... )
I will try my qt app on the pi3 in the evening (hoping my mouse interaction problem has miraculously gone away...).
Next steps for faster browser may be to try it with `gstreamer` or try the `flag _use_system_ffmpeg` ? I do not have enough understanding ...

**Comment by maitredede** [comment]
I don't have as luck as you, my build is still failing (runned twice). I started over a fresh raspbian lite image, followed README install, checked that packages were installed on host. Still the same error, Really seams to be related to cross-compilation.
Either I have a missing package or the bash for windows has a incompatibility.

I will try on a fresh Ubuntu Server 16.04 x64.

@zevero What do you mean by "faster browser" ? Do you mean hardware video decoding ?

**Comment by zevero** [comment]
Compiled my qt app and tested it on the pi.

Looks good! html5test.com gives me 507 points.
But again ... no mouse interaction for qtwebengine (only keyboard).


On starting my app I had the following issue
    
    Failed to load =/opt/vc/lib/libEGL.so.1: =/opt/vc/lib/libEGL.so.1:
    [1134:1166:0703/191218.017264:ERROR:gl_surface_qt.cpp(661)] Requested OpenGL implementation is not supported. Implementation: 0
    ...

which I solved by setting a symlink `ln -s / =` as a workaround.


@MaitreDede I was expecting qtwebengine performance in my qt app to be the same as the default chromium browser on current raspbian pixel. However (for 2017) it is embarrassingly slow. CPU or bandwith are definitely not the problem ... it is basically sitting around and a page load often takes 20s or more.
As a javascript, mongodb, php, mysql programmer I have not so much insight in the inner workings and in compiling web browsers. However I was hoping that by using "hardware acc" it would be faster somehow...

**Comment by zevero** [comment]
@Kukkimonsuta why did you remove section `# fix old egl` in the dev readme?

**Comment by Kukkimonsuta** [comment]
@zevero Because I don't think it's needed in latest raspbian lite image.

**Comment by maitredede** [comment]
Finally, qtwebengine is building. Bash on Ubuntu on Windows was the problem. On a fresh Ubuntu 16.04x64 VM, it is compilling.
For piomxtextures, I had to install `libbz2-dev` on the pi to have it compile on the host.

I will do some tests later...

**Comment by Kukkimonsuta** [comment]
@MaitreDede Thank you, I forgot about `libbz2-dev`, will add it to the readme. I'm using ubuntu on windows too, gonna try it in VM now.

**Comment by Kukkimonsuta** [comment]
`dev` branch should now be building qt 5.9.1 successfully, feel free to reopen if still experiencing issues

**Comment by hardikharpal** [comment]
@zevero  I am facing same problem as u mentioned 
`Failed to load =/opt/vc/lib/libEGL.so.1: =/opt/vc/lib/libEGL.so.1:
[1134:1166:0703/191218.017264:ERROR:gl_surface_qt.cpp(661)] Requested OpenGL implementation is not supported. Implementation: 0
...`

I did 
sudo ln -s /opt/vc/lib/libEGL.so /opt/vc/lib/libEGL.so.1

sudo ln -s /opt/vc/lib/libGLESv2.so /opt/vc/lib/libGLESv2.so.2

sudo ldconfig

on raspi 3 but still getting same issue .... 


pi@raspberrypi:~ $ cd  /opt/vc/lib/

pi@raspberrypi:/opt/vc/lib $ ls

libbcm_host.so           libelftoolchain.so        libopenmaxil.so
libbrcmEGL.so            libGLESv1_CM.so         libOpenVG.so
libbrcmGLESv2.so       libGLESv2.so               libvcfiled_check.a
libbrcmOpenVG.so      libGLESv2.so.2            libvchiq_arm.so
libbrcmWFC.so            libGLESv2_static.a       libvchostif.a
libcontainers.so          libkhrn_client.a            libvcilcs.a
libdebug_sym.so         libkhrn_static.a             libvcos.so
libdebug_sym_static.a libmmal_components.so  libvcsm.so
libdtovl.so                   libmmal_core.so           libWFC.so
libEGL.so                     libmmal.so                   plugins
libEGL.so.1                  libmmal_util.so
libEGL_static.a             libmmal_vc_client.so

pi@raspberrypi:/opt/vc/lib $


libEGL.so.1, libGLESv1_CM.so , libGLESv2.so.2    are in  sky blue colour

**Comment by zevero** [comment]
I have no clue of why it tries to load the libs at =/... instead of /... but you can work around by doing a stupid 
`ln -s / =` (in root - directory)

**Comment by hardikharpal** [comment]
@zevero  Thanks It does solve that issue....

**Comment by Kukkimonsuta** [comment]
Which module still tries to load egl from `=/..`? `qtwebengine` should be fixed in `dev` branch already - it was caused by custom discovery of the path because the library is loaded runtime.

**Comment by hardikharpal** [comment]
@Kukkimonsuta for me as I have not used ur scripts .... so may be your dev branch is not causing problem. I was building qtwebengine module on ubuntu in virtual box in my windows 10 for raspi 3 ..I am on qt 5.9.2.. following PI2EGLFS note from qt....I  found your git link and it solved my one issue ...about package i have to install in ubuntu itself for cross build qtwebengine  from ur dev branch ......thank you. 😊
