### ISSUE TITLE
dev: error when updating src

### ISSUE THREAD

**Issue by maitredede** [Kukkimonsuta/rpi-buildqt#13]
Hi,
When trying to download a second time the repositories, I have errors :
```
== Download qtdeclarative ==

Entrée dans 'tests/auto/qml/ecmascripttests/test262'
fatal: Cannot change to 'clean': Aucun fichier ou dossier de ce type
Arrêt sur 'tests/auto/qml/ecmascripttests/test262' ; le script a retourné un statut non nul.
```
Can be translated as  `fatal: Cannot change to 'clean': No file or folder of this type` and `the script has returned a not null status`.

It happens on `qtdeclarative` and `qtxmlpatterns`.

**Comment by Kukkimonsuta** [comment]
There was an error in `cloneOrPull` when it came to submodules, but should be resolved in latest version (https://github.com/Kukkimonsuta/rpi-buildqt/commit/3b392559b4d59a0e93fb316fc247f9f3142d8be0).
