### ISSUE TITLE
1_download.sh uses -C option on git command but git doesn't recognize it.

### ISSUE THREAD

**Issue by travfrog** [Kukkimonsuta/rpi-buildqt#2]
I changed it to -c (lower case) and that worked.

**Comment by Kukkimonsuta** [comment]
`-c` and `-C` are not equivalent, see https://www.kernel.org/pub/software/scm/git/docs/#_options

What git version do you have? `-C` should be available since `1.8.5`

**Comment by travfrog** [comment]
Ah, i see. My version is 1.7.9.5. After updating to 2.11 it works fine. Thank you.

**Comment by travfrog** [comment]
Thanks for getting back to me Lukas. I've managed to get to 3.0. The build
completes but the configuration test loses its mind.  Any thoughts? (the
odd characters are being displayed)

Thank you in advance.

my g++ version is g++ (Ubuntu/Linaro 4.7.3-2ubuntu1~12.04) 4.7.3


Running configuration tests...
Checking for gold linker...
+ cd /home/rjackson/raspi/src/qtbase/config.tests &&
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
-fuse-ld=gold -o conftest-out conftest.cpp
>
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
1:
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
ELF : not found
>
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
2:
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
cannot open
                                               : No such file
>
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
2:
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
@ @@@@@0 0 p p @p @ @@4�
                                                                4�
                                                                  : not
found
>
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
3:
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
Syntax error: word unexpected (expecting ")")
test config.qtbase.tests.use_gold_linker FAILED
Checking for machine tuple...
+
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
-dumpmachine
>
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
1:
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
ELF : not found
>
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
2:
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
cannot open
                                               : No such file
>
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
2:
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
@ @@@@@0 0 p p @p @ @@4�
                                                                4�
                                                                  : not
found
>
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
3:
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
Syntax error: word unexpected (expecting ")")
test config.qtbase.tests.machineTuple FAILED
Checking for valid makespec...
+ cd /home/rjackson/raspi/src/qtbase/config.tests/common/verifyspec &&
/home/rjackson/raspi/src/qtbase/bin/qmake "CONFIG -= qt debug_and_release
app_bundle lib_bundle" "CONFIG += shared console" "QMAKE_CFLAGS +=
--sysroot=/home/rjackson/raspi/sysroot" "QMAKE_CXXFLAGS +=
--sysroot=/home/rjackson/raspi/sysroot" "QMAKE_LFLAGS +=
--sysroot=/home/rjackson/raspi/sysroot" -early "CONFIG += cross_compile"
/home/rjackson/raspi/src/qtbase/config.tests/common/verifyspec
> Info: creating stash file
/home/rjackson/raspi/src/qtbase/config.tests/.qmake.stash
> /home/rjackson/raspi/src/qtbase/mkspecs/features/toolchain.prf:129:
Variable QMAKE_CXX.COMPILER_MACROS is not defined.
+ cd /home/rjackson/raspi/src/qtbase/config.tests/common/verifyspec &&
MAKEFLAGS= /usr/bin/make
>
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
-c -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8
-mfloat-abi=hard --sysroot=/home/rjackson/raspi/sysroot -O2 -Wall -W -fPIC
 -I. -I/home/rjackson/raspi/src/qtbase/mkspecs/devices/linux-rpi3-g++ -o
verifyspec.o verifyspec.cpp
>
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
1:
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
ELF : not found
>
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
2:
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
cannot open
                                               : No such file
>
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
2:
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
@ @@@@@0 0 p p @p @ @@4�
                                                                4�
                                                                  : not
found
>
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
3:
/home/rjackson/raspi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.real:
Syntax error: word unexpected (expecting ")")
> make: *** [verifyspec.o] Error 2
Note: Also available for Linux: linux-clang linux-kcc linux-icc linux-cxx

ERROR: Cannot compile a minimal program. The toolchain or QMakeSpec is
broken.

**Comment by Kukkimonsuta** [comment]
Version of your g++ should be irrelevant since we are using precompiled toolchain downloaded and patched in `1_download.sh`.

Are you running the script `3.0_build_qtbase.sh` or `./configure` / `make` manually?

**Comment by travfrog** [comment]
Running the scripts.

The only variables I modified in env.sh is the IP address of the Pi.

**Comment by Kukkimonsuta** [comment]
Maybe re-check that `2_sync.sh` successfully copied all files from the pi `/lib`, `/usr/include`, `/usr/lib`, `/opt/vc` to sysroot, but other than that I'm sorry, I don't know.

**Comment by travfrog** [comment]
Okay, well thanks for looking into it for me. Congrats on getting it to
work. Many people have spent many days. I'm already on day 3 and no closer.

Regards,
Richard

**Comment by Kukkimonsuta** [comment]
I understand the pain, it took me few days to get it running too. Would it help you if I published binaries built on and for ubuntu 16.04 x64 and rpi3?

**Comment by travfrog** [comment]
It would help. I think my problem is my Linux distro is a VM on my Windows
laptop and it's way out of date - like 12.04. I suspect that's where I'm
falling down. I have a new machine waiting to be set up so I'll get 16.04
on it and try again.

Actually, my friend just succeeded and he's using 16.04  - I guess that
answers that.

So what are you intending on doing with your Qt based Pi?

**Comment by Kukkimonsuta** [comment]
https://github.com/Kukkimonsuta/rpi-buildqt/releases/tag/20170317

I'm not sure if it's gonna be of any help since it's built for different ubuntu version, but it's worth a shot. Glad to hear your friend successfully built it.

We were doing experiments with video playback on some devices including rpi for one of our customers, but can't tell the specifics :)

**Comment by travfrog** [comment]
Haha, understood. Thanks for the binary and good luck.
