### ISSUE TITLE
QtBase configure failed after setup custom Qt5.9 

### ISSUE THREAD

**Issue by yangjunsong** [Kukkimonsuta/rpi-buildqt#23]
Hi, 
Recently found that "3.0_build_qtbase.sh" failed at step configure and report : "No device matching 'linux-rpi3-g++'". However it worked perfectly with Qt5.8.
Finally I found that change "3.0_build_qtbase.sh" as below will help:
1. open env.sh with your text editor
2. replace "DEVICE=linux-rpi3-g++" with "DEVICE=linux-rasp-pi3-g++"
I don't know why it works, but it seems that the build scripts don't work well with newest Qt version.

**Comment by Kukkimonsuta** [comment]
Version in `master` is for building Qt5.8

For building Qt5.9 you should use `dev` where this is taken care of:

https://github.com/Kukkimonsuta/rpi-buildqt/blob/dev/scripts/3.1_build_qtbase.sh
