### ISSUE TITLE
Issue on PI Zero

### ISSUE THREAD

**Issue by lctasca** [Kukkimonsuta/rpi-buildqt#3]
Hello there!

First I would like to congratulate for such a complete and organized tutorial.
But unfortunately I can manage to make it work for PI Zero (set it as pi1 on env.sh).
I managed to make it work until step 3.0_build_qtbase without errors when it fails to compile with message:
[error.txt](https://github.com/Kukkimonsuta/rpi-buildqt/files/923963/error.txt)

I'm not so familiar with cross compiling like you seems but seems something wrong with directories you fixed with the python script?

Thanks in advance for some clue...

Regards!

Laurence

**Comment by Kukkimonsuta** [comment]
Hi, that looks like something is wrong with the tooling. Can you please try the previous steps again and paste full output? Also can you paste your scripts/env.sh (without pi ip/account/pw of course).

**Comment by lctasca** [comment]
Hi there!

Thanks for the quick response. Bellow the files you asked for. I see no problem in post the env.sh with pi ip/user/pw since is in my internal network (behind a firewall) and the user and passwords are the default since pi is almost at default state. 

Hope this helps you to give me a clue...

Cheers

[env.txt](https://github.com/Kukkimonsuta/rpi-buildqt/files/924585/env.txt)
[1_download.txt](https://github.com/Kukkimonsuta/rpi-buildqt/files/924603/1_download.txt)
[2_sync.txt](https://github.com/Kukkimonsuta/rpi-buildqt/files/924604/2_sync.txt)
[3.0_build_qtbase.txt](https://github.com/Kukkimonsuta/rpi-buildqt/files/924605/3.0_build_qtbase.txt)

**Comment by Kukkimonsuta** [comment]
I don't see anything obvious wrong.. what OS are you using?

**Comment by lctasca** [comment]
Ubuntu 16.04 (32 bits) + Raspian Jessie 2017-01-11.

What I think is the most strange part is the not printable characteres in log 3.0...

**Comment by Kukkimonsuta** [comment]
Aha! I'm sorry, but that is the issue, you need to use 64 bit host system because that's what the toolchain this tutorial is using is built for. I'll add a note to the readme.

**Comment by lctasca** [comment]
Hum... Are you sure is that the case? Could it be related to character coding? I'm still suspicious about the not printable characters... 

I'll try again tomorrow with a 64 bit host and feedback if that is the case

**Comment by Kukkimonsuta** [comment]
Yes, I'm sure:

This is from toolchain used (with gcc 4.9.3):
```
file ./arm-linux-gnueabihf-g++.real
./arm-linux-gnueabihf-g++.real: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=be500fb8871d87f56238cfa3fa6a6a0ad58e3fb2, stripped
```

This is from older 32bit toolchain (with incompatible gcc):
```
file ./arm-linux-gnueabihf-g++
./arm-linux-gnueabihf-g++: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.15, stripped
```

**Comment by lctasca** [comment]
Wow!

Thanks for pointing that!

There is any chance to make this tutorial work on a 32bit host?

**Comment by Kukkimonsuta** [comment]
The crosstool ng config is included within the tools repo (https://github.com/raspberrypi/tools/blob/master/configs/arm-rpi-4.9.3-linux-gnueabihf.config), so you may be able to build yourself a 32bit version, but I can't provide much support on doing that as I have zero experience with it.

I think the best path is to just upgrade to 64bit ubuntu.

Alternatively if you are using `Windows 10 Creators Update` you may actually be able to build it in the Windows Subsystem for Linux (beta), but I haven't tested it yet, so it might not work. The WSL is also available in the `Anniversary Update`, but less stable and including older version of ubuntu 14 I think.

**Comment by lctasca** [comment]
Deadly sure I'll try with 64 bit Ubuntu and let you know about the results.

I give up to cross compile from windows since it seams more uncommon along developers and so there are fewer tutorials and none works barely for me.

Anyway, thanks a lot for the clues very kind of you!

Regards!

**Comment by Kukkimonsuta** [comment]
May I ask whether you've successful with building for pi zero? Can this issue be closed now?

**Comment by lctasca** [comment]
Hi

Indeed I successfully cross compile to RPi Zero using Ubuntu 64 and your guide thanks. I just made some small modifications:

• Since I use normal Rapian Jessie (not lite) the 2_sync script fails because of VNC. Solve that by change line 24 of Copy /usr/lib to exclude VNC (not sure if this applicable to change but this can make your guide more "generic"):

rsync -avztr --delete --rsh="/usr/bin/sshpass -p ${RPIDEV_DEVICE_PW} ssh -o StrictHostKeyChecking=no -l ${RPIDEV_DEVICE_USER}" ${RPIDEV_DEVICE_ADDRESS}:/usr/lib ${RPIDEV_SYSROOT}/usr **--exclude 'vnc'**

• Lines 14 and 15 had no effect on 3.0_build_qtbase scrip. I modified them to rm -rf ${QT_INSTALL_DIR} and rm -rf ${QT_INSTALL_DIR_HOST} to successfully clean previous build (delete directories).

With this two small modifications above you guide works like charm in here and you can consider this issue closed.

**BUT** my objective was to cross compile to use webview component in RPi and so I was trying to extend your guide to use qtwebkit ([CrossCompileGuide.txt](https://github.com/Kukkimonsuta/rpi-buildqt/files/947306/CrossCompileGuide.txt)) by modifying download script ([1_download.txt](https://github.com/Kukkimonsuta/rpi-buildqt/files/947339/1_download.txt)) and adding qtwebkit script ([3.5_build_qtwebkit.txt](https://github.com/Kukkimonsuta/rpi-buildqt/files/947340/3.5_build_qtwebkit.txt)) . And failing by got some problems in compiling 3.1_build_qtdeclarative script ([copile_error.txt](https://github.com/Kukkimonsuta/rpi-buildqt/files/947325/copile_error.txt)) that's why I didn't feedback you early.

Like I said before you may consider this issue closed but I appreciate any clue regard adding webkit to the cross compile guide. Thanks for all the help!

Laurence

**Comment by Kukkimonsuta** [comment]
`/home/laurence/raspi/sysroot/usr/lib/arm-linux-gnueabihf/libQt5Quick.so.5: undefined reference to`

I think there aren't supposed to be any qt libs in the sysroot, I think it's picking wrong libraries.

**Comment by lctasca** [comment]
Hum... Have any idea of why? The most strange part is that this script successfully compile previously. The only thing I changes is add more library as described in the cross compile guide posted above. 

Laurence

**Comment by Kukkimonsuta** [comment]
No idea.. also note that if you are rebuilding you should run `1_download.sh` again which will reset and clean all repos. Alternatively `make clean` in specific repo might also work.

I've tried building qtwebkit but got some errors about not supporting ARM architecture which I don't know how to get around.

**Comment by lctasca** [comment]
Well, we seam in a dead end for now but I thank you again for all the help and support. For the moment I got around the project by implementing in a different way. Once I get back to this solution and solve it I'll let you now.

Best regards

Laurence
