### ISSUE TITLE
libavutil/avutil.h

### ISSUE THREAD

**Issue by zevero** [Kukkimonsuta/rpi-buildqt#6]
Hi,
we have been doing our own scripts for qt 5.6 on arch but they do not work anymore for qt 5.8. And we did not get hardware acceleration running. We very much hope, that your scripts will help us. They are very convenient. Thank you!

However, I have a problem at the last step with libavutil/avutil.h

I am using Debian Stretch 64bit and current raspian jessie lite on rpi3

Funny thing is that it says
INSTALL libavutil/avutil.h prior to not beeing able to find ist...

---- Here is the log ----

./4_build_piomxtextures.sh 

== Prepare 3rd party ==

Cloning dependency: LightLogger...
Klone nach 'LightLogger' ...
remote: Counting objects: 90, done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 90 (delta 5), reused 79 (delta 5), pack-reused 0
Entpacke Objekte: 100% (90/90), Fertig.
-I/tmp/sd-kukki/raspi/sysroot/usr/include/samba-4.0 -L/tmp/sd-kukki/raspi/sysroot/usr/lib/arm-linux-gnueabihf -lsmbclient
-L/tmp/sd-kukki/raspi/sysroot/usr/lib/arm-linux-gnueabihf -lssh
Building for pi2...
Downloading ffmpeg sources from git...
Klone nach 'ffmpeg_src' ...
remote: Counting objects: 6155, done.
remote: Compressing objects: 100% (4799/4799), done.
remote: Total 6155 (delta 1520), reused 4117 (delta 1164), pack-reused 0
Empfange Objekte: 100% (6155/6155), 13.17 MiB | 902.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (1520/1520), Fertig.
Hinweis: Checke 'd4b731e271ba944ade8f6a128271479529507de9' aus.

Sie befinden sich im Zustand eines 'lösgelösten HEAD'. Sie können sich
umschauen, experimentelle Änderungen vornehmen und diese committen, und
Sie können alle möglichen Commits, die Sie in diesem Zustand machen,
ohne Auswirkungen auf irgendeinen Branch verwerfen, indem Sie einen
weiteren Checkout durchführen.

Wenn Sie einen neuen Branch erstellen möchten, um Ihre erstellten Commits
zu behalten, können Sie das (jetzt oder später) durch einen weiteren Checkout
mit der Option -b tun. Beispiel:

  git checkout -b <neuer-Branchname>

Configuring...
Prefix to /tmp/sd-kukki/raspi/src/piomxtextures/3rdparty/ffmpeg/ffmpeg_src...
install prefix            /tmp/sd-kukki/raspi/src/piomxtextures/3rdparty/ffmpeg/ffmpeg_src/ffmpeg_compiled
source path               .
C compiler                arm-linux-gnueabihf-gcc
C library                 glibc
host C compiler           gcc
host C library            glibc
ARCH                      arm (armv7-a)
big-endian                no
runtime cpu detection     no
ARMv5TE enabled           yes
ARMv6 enabled             yes
ARMv6T2 enabled           yes
VFP enabled               yes
NEON enabled              yes
THUMB enabled             no
debug symbols             no
strip symbols             yes
optimize for size         no
optimizations             yes
static                    yes
shared                    yes
postprocessing support    no
new filter support        yes
network support           yes
threading support         pthreads
safe bitstream reader     yes
SDL2 support              no
opencl enabled            no
JNI support               no
texi2html enabled         no
perl enabled              yes
pod2man enabled           yes
makeinfo enabled          yes
makeinfo supports HTML    yes

Enabled programs:

External libraries:
bzlib			   libssh		      openssl			 xlib			    zlib
iconv

External libraries providing hardware acceleration:

Libraries:
avcodec			   avfilter		      avutil			 swresample		    swscale
avdevice		   avformat

Enabled decoders:
aac			   alias_pix		      g729			 pcm_dvd		    shorten
aac_fixed		   als			      gsm			 pcm_f32be		    sipr
aac_latm		   amrnb		      gsm_ms			 pcm_f32le		    smackaud
ac3			   amrwb		      h264			 pcm_f64be		    smacker
ac3_fixed		   ape			      hap			 pcm_f64le		    smvjpeg
adpcm_4xm		   apng			      hnm4_video		 pcm_lxf		    sol_dpcm
adpcm_adx		   ass			      hq_hqa			 pcm_mulaw		    sonic
adpcm_afc		   atrac1		      hqx			 pcm_s16be		    srt
adpcm_aica		   atrac3		      iac			 pcm_s16be_planar	    ssa
adpcm_ct		   atrac3p		      imc			 pcm_s16le		    stl
adpcm_dtk		   bink			      interplay_acm		 pcm_s16le_planar	    subrip
adpcm_ea		   binkaudio_dct	      interplay_dpcm		 pcm_s24be		    subviewer
adpcm_ea_maxis_xa	   binkaudio_rdft	      interplay_video		 pcm_s24daud		    subviewer1
adpcm_ea_r1		   bmv_audio		      jacosub			 pcm_s24le		    tak
adpcm_ea_r2		   brender_pix		      m101			 pcm_s24le_planar	    targa_y216
adpcm_ea_r3		   ccaption		      mace3			 pcm_s32be		    tdsc
adpcm_ea_xas		   cfhd			      mace6			 pcm_s32le		    text
adpcm_g722		   comfortnoise		      magicyuv			 pcm_s32le_planar	    truehd
adpcm_g726		   cook			      metasound			 pcm_s64be		    truemotion2rt
adpcm_g726le		   dca			      microdvd			 pcm_s64le		    truespeech
adpcm_ima_amv		   dds			      mjpeg			 pcm_s8			    tta
adpcm_ima_apc		   dsd_lsbf		      mjpegb			 pcm_s8_planar		    twinvq
adpcm_ima_dat4		   dsd_lsbf_planar	      mlp			 pcm_u16be		    vmdaudio
adpcm_ima_dk3		   dsd_msbf		      movtext			 pcm_u16le		    vorbis
adpcm_ima_dk4		   dsd_msbf_planar	      mp1			 pcm_u24be		    vp6
adpcm_ima_ea_eacs	   dsicinaudio		      mp1float			 pcm_u24le		    vp6f
adpcm_ima_ea_sead	   dss_sp		      mp2			 pcm_u32be		    vp7
adpcm_ima_iss		   dst			      mp2float			 pcm_u32le		    vp8
adpcm_ima_oki		   dvaudio		      mp3			 pcm_u8			    vp9
adpcm_ima_qt		   dvbsub		      mp3adu			 pcm_zork		    vplayer
adpcm_ima_rad		   dvdsub		      mp3adufloat		 pgssub			    vqa
adpcm_ima_smjpeg	   dxv			      mp3float			 pjs			    wavpack
adpcm_ima_wav		   eac3			      mp3on4			 prores_lgpl		    webvtt
adpcm_ima_ws		   eacmv		      mp3on4float		 qcelp			    wmalossless
adpcm_ms		   eamad		      mpc7			 qdm2			    wmapro
adpcm_mtaf		   eatgq		      mpc8			 ra_144			    wmav1
adpcm_psx		   eatgv		      mpeg1video		 ra_288			    wmav2
adpcm_sbpro_2		   eatqi		      mpeg2video		 ralf			    wmavoice
adpcm_sbpro_3		   eightbps		      mpegvideo			 realtext		    ws_snd1
adpcm_sbpro_4		   eightsvx_exp		      mpl2			 roq_dpcm		    xan_dpcm
adpcm_swf		   eightsvx_fib		      mvc1			 rscc			    xface
adpcm_thp		   evrc			      nellymoser		 s302m			    xl
adpcm_thp_le		   ffwavesynth		      on2avc			 sami			    xma1
adpcm_vima		   fic			      opus			 screenpresso		    xma2
adpcm_xa		   flac			      paf_audio			 sdx2_dpcm		    xsub
adpcm_yamaha		   fourxm		      pcm_alaw			 sgirle			    ylc
aic			   g2m			      pcm_bluray		 sheervideo		    zero12v
alac			   g723_1

Enabled encoders:

Enabled hwaccels:

Enabled parsers:
aac			   dirac		      g729			 mlp			    rv30
aac_latm		   dnxhd		      gsm			 mpeg4video		    rv40
ac3			   dpx			      h261			 mpegaudio		    tak
adx			   dvaudio		      h263			 mpegvideo		    vorbis
bmp			   dvbsub		      h264			 opus			    vp3
cavsvideo		   dvd_nav		      hevc			 png			    vp8
cook			   dvdsub		      mjpeg			 pnm			    vp9
dca			   flac

Enabled demuxers:
aa			   dtshd		      image_png_pipe		 nsv			    smjpeg
aac			   dv			      image_ppm_pipe		 nut			    smush
ac3			   dvbsub		      image_qdraw_pipe		 nuv			    sol
acm			   dvbtxt		      image_sgi_pipe		 ogg			    sox
act			   dxa			      image_sunrast_pipe	 oma			    spdif
adf			   ea			      image_tiff_pipe		 paf			    srt
adp			   ea_cdata		      image_webp_pipe		 pcm_alaw		    stl
ads			   eac3			      ingenient			 pcm_f32be		    str
adx			   epaf			      ipmovie			 pcm_f32le		    subviewer
aea			   ffm			      ircam			 pcm_f64be		    subviewer1
afc			   ffmetadata		      iss			 pcm_f64le		    sup
aiff			   filmstrip		      iv8			 pcm_mulaw		    svag
aix			   flac			      ivf			 pcm_s16be		    swf
amr			   flic			      ivr			 pcm_s16le		    tak
anm			   flv			      jacosub			 pcm_s24be		    tedcaptions
apc			   fourxm		      jv			 pcm_s24le		    thp
ape			   frm			      live_flv			 pcm_s32be		    threedostr
apng			   fsb			      lmlm4			 pcm_s32le		    tiertexseq
aqtitle			   g722			      loas			 pcm_s8			    tmv
asf			   g723_1		      lrc			 pcm_u16be		    truehd
asf_o			   g729			      lvf			 pcm_u16le		    tta
ass			   genh			      lxf			 pcm_u24be		    tty
ast			   gif			      m4v			 pcm_u24le		    txd
au			   gsm			      matroska			 pcm_u32be		    v210
avi			   gxf			      mgsts			 pcm_u32le		    v210x
avr			   h261			      microdvd			 pcm_u8			    vag
avs			   h263			      mjpeg			 pjs			    vc1t
bethsoftvid		   h264			      mlp			 pmp			    vivo
bfi			   hevc			      mlv			 pva			    vmd
bfstm			   hls			      mm			 pvf			    vobsub
bink			   hnm			      mmf			 qcp			    voc
bintext			   ico			      mov			 r3d			    vpk
bit			   idcin		      mp3			 rawvideo		    vplayer
bmv			   idf			      mpc			 realtext		    vqf
boa			   iff			      mpc8			 redspark		    w64
brstm			   ilbc			      mpegps			 rl2			    wav
c93			   image2		      mpegts			 rm			    wc3
caf			   image2_alias_pix	      mpegtsraw			 roq			    webm_dash_manifest
cavsvideo		   image2_brender_pix	      mpegvideo			 rpl			    webvtt
cdg			   image2pipe		      mpjpeg			 rsd			    wsaud
cdxl			   image_bmp_pipe	      mpl2			 rso			    wsd
cine			   image_dds_pipe	      mpsub			 rtp			    wsvqa
concat			   image_dpx_pipe	      msf			 rtsp			    wtv
data			   image_exr_pipe	      msnwc_tcp			 sami			    wv
daud			   image_j2k_pipe	      mtaf			 sap			    wve
dcstr			   image_jpeg_pipe	      mtv			 sbg			    xa
dfa			   image_jpegls_pipe	      musx			 sdp			    xbin
dirac			   image_pam_pipe	      mv			 sdr2			    xmv
dnxhd			   image_pbm_pipe	      mvi			 segafilm		    xvag
dsf			   image_pcx_pipe	      mxf			 shorten		    xwma
dsicin			   image_pgm_pipe	      mxg			 siff			    yop
dss			   image_pgmyuv_pipe	      nc			 sln			    yuv4mpegpipe
dts			   image_pictor_pipe	      nistsphere		 smacker

Enabled muxers:

Enabled protocols:
async			   file			      icecast			 rtmpe			    subfile
cache			   ftp			      libssh			 rtmps			    tcp
concat			   gopher		      md5			 rtmpt			    tee
crypto			   hls			      mmsh			 rtmpte			    tls_openssl
data			   http			      mmst			 rtmpts			    udp
ffrtmpcrypt		   httpproxy		      pipe			 rtp			    udplite
ffrtmphttp		   https		      rtmp			 srtp			    unix

Enabled filters:

Enabled bsfs:
aac_adtstoasc		   h264_mp4toannexb	      mjpeg2jpeg		 mp3_header_decompress	    remove_extradata
chomp			   hevc_mp4toannexb	      mjpega_dump_header	 mpeg4_unpack_bframes	    text2movsub
dca_core		   imx_dump_header	      mov2textsub		 noise			    vp9_superframe
dump_extradata

Enabled indevs:

Enabled outdevs:

License: nonfree and unredistributable
Creating config.mak, config.h, and doc/config.texi...

WARNING: Option --disable-decoder=libstagefright_h264 did not match anything
WARNING: Option --disable-decoder=iff_byterun1 did not match anything
Building...
CC	libavdevice/alldevices.o
CC	libavdevice/avdevice.o
CC	libavdevice/utils.o

.....

INSTALL	libavutil/avstring.h
INSTALL	libavutil/avutil.h
INSTALL	libavutil/base64.h

.....

INSTALL	libavutil/libavutil.pc
Cleaning up...
Done! Bye bye! ;-)
All done. Bye bye ;-)

== Configuring piomxtextures ==

Info: creating stash file /tmp/sd-kukki/raspi/src/piomxtextures/.qmake.stash

== Building piomxtextures ==
...

In file included from ../piomxtextures_src/omxplayer_lib/OMXPlayerAudio.h:25:0,
                 from ../piomxtextures_src/omx_playeraudio.h:30,
                 from ../piomxtextures_src/omx_mediaprocessor.cpp:38:
../piomxtextures_src/omxplayer_lib/DllAvUtil.h:38:34: fatal error: libavutil/avutil.h: No such file or directory
     #include <libavutil/avutil.h>
                                  ^
compilation terminated.
Makefile:3383: die Regel für Ziel „omx_mediaprocessor.o“ scheiterte
make[1]: *** [omx_mediaprocessor.o] Fehler 1
make[1]: *** Es wird auf noch nicht beendete Prozesse gewartet...

... (it fails several times)

**Comment by zevero** [comment]
searching for avutil  brings the following /tmp/sd-kukki/raspi$ find -name "avutil.h"

./src/piomxtextures/3rdparty/ffmpeg/ffmpeg_src/libavutil/avutil.h
./src/piomxtextures/3rdparty/ffmpeg/ffmpeg_src/ffmpeg_compiled/include/libavutil/avutil.h
./src/piomxtextures/3rdparty/ffmpeg/ffmpeg_pi2/include/libavutil/avutil.h

**Comment by Kukkimonsuta** [comment]
I've updated the script for pot 5.6.0 and rpi3 which seems to work for me. Can you retry please?

**Comment by misterbig** [comment]
thank you, now it works here on rpi3

**Comment by zevero** [comment]
Thank you! Compilation worked!
